### ISSUE TITLE
Empty extension in illustrator

### ISSUE THREAD

**Issue by Eden31** [yasashiku/hanpuku#2]
Hello,

First of all thanks for this great plugin which seems to be perfect for me.

Just something i don't understand. I followed the steps of install using the Terminal but when i launch AI and then the extension the dedicated hanpuku window is empty.  

Thanks by advance for any answer.

Best,

Damien

<img width="553" alt="capture d ecran 2016-04-04 a 14 09 23" src="https://cloud.githubusercontent.com/assets/15089033/14247570/3d0d936c-fa6f-11e5-8b3b-e81b8ca960c9.png">

**Comment by alex-r-bigelow** [comment]
Thanks for your interest!

Hmm... that's very odd. With the hanpuku widget open, if you open a browser and go to http://localhost:8088, you should see an index.html link. If you click it, it will pull up Chrome's developer tools—I'm hoping there's some kind of error message in the console.

**Comment by Eden31** [comment]
Alex,
I think there's a problem with the install procedure because i got nothing on my localhost (nothing is running) with the hanpuku widget open.

I'm on OS X El Captain.

Thanks for your help.

Damien

**Comment by alex-r-bigelow** [comment]
Right... I completely forgot to enable the debug mode in those instructions. I should probably put them in the README for now anyway. I'll fix this asap.

**Comment by alvvvvvin** [comment]
Hi @alex-r-bigelow, I've followed the changes from the README above, but I'm still getting an empty Hanpuku dialogue box. Can you point me in the right direction as to how to resolve?

![screen shot 2017-01-12 at 5 22 23 pm](https://cloud.githubusercontent.com/assets/3296514/21910866/ee256926-d8eb-11e6-9c01-c438c63913e9.png)
![screen shot 2017-01-12 at 5 22 09 pm](https://cloud.githubusercontent.com/assets/3296514/21910865/ee24b0f8-d8eb-11e6-8a92-50d939f206f3.png)

**Comment by alex-r-bigelow** [comment]
@alvvvvvin, sorry about the delay!

I can't seem to reproduce this... is Illustrator up to date?

If it's not a version problem, with the empty hanpuku window open, could I get you to open a web browser and navigate to [http://localhost:8088](http://localhost:8088) and see if there are any errors in the Console tab?

**Comment by alex-r-bigelow** [comment]
This should be fixed with the new ZXPInstaller approach; I'll close this for now (but feel free to reopen if it's still a problem).
