### ISSUE TITLE
Manifest.xml wasn't compatible with CEP 7

### ISSUE THREAD

**Issue by CameronLamont** [yasashiku/hanpuku#3]
I was trying to get the extension working but couldn't get it to appear in the extensions menu until i updated the manifest.xml

 <HostList>
                      <Host Name="ILST" Version="19.0"/>
     </HostList>

I found the reference here
https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_7.x/CEP_7.0_HTML_Extension_Cookbook.pdf
under Extension Manifest.  I was able to load the example and work my way from there.

Apparently in CEP 7 the XSD asks for each version individually instead of inside square brackets.  Similarly the update for debugging is '7' instead of '6'.  (I'm using Windows so it was a regedit update). 

I tried having both manifests but it wouldn't load.  On my other (windows) PC it worked without any changes - potentially i hadn't updated Creative Cloud in a while.

Only just getting to play with it - great idea - if I find anymore windows quirks I can pass them onto you (so you don't have to worry if they are low priority)

**Comment by CameronLamont** [comment]
UPDATE: It isn't the square brackets.  I was using Illustrator 20.1 and it hadn't come under the bracketed versions.  Seems I was 'hearing zebras'

**Comment by alex-r-bigelow** [comment]
Thanks for exploring + documenting + fixing this!

Let me know if you encounter further issues.
