### ISSUE TITLE
Trouble installing Hanpuku Ai 2017 21.0.0

### ISSUE THREAD

**Issue by james2468** [yasashiku/hanpuku#4]
<img width="499" alt="screen shot 2016-11-17 at 6 00 15 pm" src="https://cloud.githubusercontent.com/assets/1417049/20411505/c4bc80ba-acef-11e6-82c8-8bcfe743ddc2.png">

Looks like it's in the right directory but not showing up in the extensions window with document open. It's a new document that's empty. Would that matter? else don't know what's wrong.

Edited the plist file as shown with BBEdit unicode-8 (No BOM).

<img width="439" alt="screen shot 2016-11-17 at 6 09 06 pm" src="https://cloud.githubusercontent.com/assets/1417049/20411792/1758622a-acf1-11e6-8253-7b71d3032597.png">

**Comment by alex-r-bigelow** [comment]
@james2468, sorry for the delay!

I've tried this several ways and I'm still can't seem to reproduce the problem. Having the directory there should work...

Did you try installing via the [Add-Ons](https://creative.adobe.com/addons/products/15087) page?

**Comment by alex-r-bigelow** [comment]
This should be fixed with the new ZXPInstaller approach; I'll close this for now (but feel free to reopen if it's still a problem).
