### ISSUE TITLE
Using with localhost?

### ISSUE THREAD

**Issue by petulla** [yasashiku/hanpuku#6]
Hi there

I'm trying to use this with a project served locally. I noticed all of your examples are with remote repos or by navigating to a specific file path. In my use case, the project is compiled server-side, creating a unique localhost url but not a file path url where the project can be previewed. How well does this plugin support projects at paths like: localhost:8000/project/child.html where the assets are also being served from localhost paths.

**Comment by alex-r-bigelow** [comment]
Sorry, I"m really confused by your use case... this project is an Adobe Illustrator plugin, so its notion of "server" and "client" are a little wonky... it's really only designed to support running client-side D3 code inside Illustrator.

I could be wrong, but it sounds like you want to generate D3 code (to include in server-side rendering) from things you've drawn in Illustrator? If so, that's really interesting, and a new project that I'm working on might be a better fit (unfortunately I probably won't have anything in that space for a couple years... solo grad student programmer problems). I've found that you can _kind of_ achieve that kind of workflow if you export an SVG from something like Inkscape (Illustrator's SVG export takes extreme liberties with formatting, and trashes any metadata you've added)... there are some examples of this kind of workflow in this [blog post](http://christopheviau.com/d3_tutorial/d3_inkscape/)

Also, I'm really sorry if my responses are slow; I'm travelling for the next few weeks and connectivity is sparse / slow.

**Comment by petulla** [comment]
My use case is that the d3 code is rendered in a django app. So my code is served at a route on localhost. I want to load that url in illustrator.

**Comment by alex-r-bigelow** [comment]
Hanpuku only supports running copy/pasted d3 code into the code window in the extension (or, in a few cases, you can get examples from bl.ocks.org to auto-import), and it's rendered directly inside Illustrator. In each case, we're just extracting the d3 source code itself and rendering that inside Illustrator, not extracting stuff from a rendered webpage (for that, you might want to check out D3 Deconstructor and/or SVG Crowbar).

**Comment by alex-r-bigelow** [comment]
Closing for now; if that didn't answer your question, please feel free to reopen. Thanks again for asking!
